### ISSUE TITLE
请问是否可以用于中文关键词提取?

### ISSUE THREAD

**Issue by Dielianss** [thunlp/BERT-KPE#10]
请问 BERT-KPE 可以用于中文关键词提取吗?

**Comment by Dielianss** [comment]
嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月1日(周二) 中午1:23
收件人: ***@***.***&gt;;
抄送: "Jie ***@***.******@***.***&gt;;
主题: Re: [thunlp/BERT-KPE] 请问是否可以用于中文关键词提取? (#10)




 
方法可以迁移到中文关键词抽取上，但是预训练模型与分词预处理等需要适配一下

**Comment by SunSiShining** [comment]
you are welcome :)

**Comment by luomuqinghan** [comment]
> 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！

您好，请问中文分词后（按照单个字），需要把对应的start-position与end-position的值按照“字”重新组织来构建label吗？ 而不能使用传统的分词结果来构建start-position与end-position？

**Comment by SunSiShining** [comment]
Hi, 我没太明白你的问题。

用不同方式构建label span，只要能从model ouputs中直接或间接提取true keyphrase span， 应该都是可行的，但可能存在性能差异 (需要实验)。

**Comment by luomuqinghan** [comment]
> Hi, 我没太明白你的问题。
> 
> 用不同方式构建label span，只要能从model ouputs中直接或间接提取true keyphrase span， 应该都是可行的，但可能存在性能差异 (需要实验)。

谢谢您的回答。

我的意思是，propress.py处理之后，词语的start-position与end-position是根据propress.py中的**分词方式**来构建的。
模型里的chunk_label和phrase-label是根据start-position与end-position来构建的。
但是模型里根据**bert分词**后，采用n-grams的方式提取特征，对每一个n-gram采用标签有监督的训练。

这两种不同的分词方式可能造成不同的分词结果，这对有监督的学习不会造成影响吗？还是说，label的构建与使用和分词方式无关？

中文亦是如此，propress.py中的中文分词与Bert分词结果不同，那么构建的start-position与end-position能用于监督模型训练吗？

**Comment by SunSiShining** [comment]
Hi, 以英文为例

Given a sentence "{A} {B} {C} {D}" that has four words, {B}{C} is the true keyphrase, their start and end positions are 1 and 2.
* BERT分词后：{A} {B} {C1 C2} {D1 D2 D3}
* RoBERTa分词后：{A1' A2'} {B1' B2'} {C1' C2' C3'} {D1' D2'}

虽然分词结果不同，但我们后面跟的classification layer只会基于first sub-token embeddings进行分类 (we consider the first sub-token embedding as the word representation)，即: 

* BERT: {A} {B} {C1} {D1}
* RoBERTa: {A1'} {B1'} {C1'} {D1'}

因此即使使用不同的tokenizers, the true keyphrase在整个句子中的start&end positions仍旧是1 & 2.

希望这样有解答到您的问题

**Comment by Graduo** [comment]
> 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> […](#)

请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~

**Comment by SunSiShining** [comment]
目前我们这边没有进行中文尝试，您可与这条留言作者联系一下哈

**Comment by Dielianss** [comment]
> > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > […](#)
> 
> 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~

您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!

**Comment by Graduo** [comment]
> > > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > > […](#)
> > 
> > 
> > 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~
> 
> 您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!

您好，我这边目前打算是自己标注一些数据集。其他公开的确实没有找到合适的数据集，打算试一些命名实体识别（比如https://github.com/yuankeyi/2019-SOHU-Contest）或者实体链接数据集代替。可否请教您一下转换中文需要作哪些适配工作以及基于字粒度分词的bert您这边怎么处理span信息的嘛

**Comment by Dielianss** [comment]
> > > > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > > > […](#)
> > > 
> > > 
> > > 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~
> > 
> > 
> > 您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!
> 
> 您好，我这边目前打算是自己标注一些数据集。其他公开的确实没有找到合适的数据集，打算试一些命名实体识别（比如https://github.com/yuankeyi/2019-SOHU-Contest ）或者实体链接数据集代替。可否请教您一下转换中文需要作哪些适配工作以及基于字粒度分词的bert您这边怎么处理span信息的嘛

我这边的情况也和你差不多, 我也是将中文实体标注数据集迁移过来, 作为中文版 Bert-KPE 的训练/测试数据集. 至于如何完成中文的适配, 我之前是通读下作者代码里的预处理部分, 然后 按照 中文词语 对应 英文单词的方式进行适配, 例如, 中文"开心" ---> 英文"happy", 也就是说, 我是基于词粒度, 而非字粒度分词的. 我打算最近有时间的话, 就将我的代码发布到 GitHub 上, 希望到时候可以和你交流!

**Comment by Graduo** [comment]
> > > > > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > > > > […](#)
> > > > 
> > > > 
> > > > 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~
> > > 
> > > 
> > > 您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!
> > 
> > 
> > 您好，我这边目前打算是自己标注一些数据集。其他公开的确实没有找到合适的数据集，打算试一些命名实体识别（比如https://github.com/yuankeyi/2019-SOHU-Contest ）或者实体链接数据集代替。可否请教您一下转换中文需要作哪些适配工作以及基于字粒度分词的bert您这边怎么处理span信息的嘛
> 
> 我这边的情况也和你差不多, 我也是将中文实体标注数据集迁移过来, 作为中文版 Bert-KPE 的训练/测试数据集. 至于如何完成中文的适配, 我之前是通读下作者代码里的预处理部分, 然后 按照 中文词语 对应 英文单词的方式进行适配, 例如, 中文"开心" ---> 英文"happy", 也就是说, 我是基于词粒度, 而非字粒度分词的. 我打算最近有时间的话, 就将我的代码发布到 GitHub 上, 希望到时候可以和你交流!

好的，已follow~希望早点可以看到您这边中文版BERT-KPE，感谢您和 @SunSiShining 的贡献~保持交流~

**Comment by Dielianss** [comment]
> > > > > > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > > > > > […](#)
> > > > > 
> > > > > 
> > > > > 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~
> > > > 
> > > > 
> > > > 您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!
> > > 
> > > 
> > > 您好，我这边目前打算是自己标注一些数据集。其他公开的确实没有找到合适的数据集，打算试一些命名实体识别（比如https://github.com/yuankeyi/2019-SOHU-Contest ）或者实体链接数据集代替。可否请教您一下转换中文需要作哪些适配工作以及基于字粒度分词的bert您这边怎么处理span信息的嘛
> > 
> > 
> > 我这边的情况也和你差不多, 我也是将中文实体标注数据集迁移过来, 作为中文版 Bert-KPE 的训练/测试数据集. 至于如何完成中文的适配, 我之前是通读下作者代码里的预处理部分, 然后 按照 中文词语 对应 英文单词的方式进行适配, 例如, 中文"开心" ---> 英文"happy", 也就是说, 我是基于词粒度, 而非字粒度分词的. 我打算最近有时间的话, 就将我的代码发布到 GitHub 上, 希望到时候可以和你交流!
> 
> 好的，已follow~ 希望早点可以看到您这边中文版BERT-KPE，感谢您和 @SunSiShining 的贡献~ 保持交流~

您好, 抱歉让您久等了, 由于近期非常忙, 代码现在才提交,  我的实验代码放在 Chinese-BERT-KPE 这个 repo 里了,  整理得比较粗糙, 直接在作者的源代码上进行修改了, 希望可以交流, 谢谢!

**Comment by Graduo** [comment]
> > > > > > > 嗯嗯谢谢，近期已经完成中文预处理的适配，准备跑模型了！
> > > > > > > […](#)
> > > > > > 
> > > > > > 
> > > > > > 请问您这边在中文上效果怎么样呢，我目前也想迁移到中文上~
> > > > > 
> > > > > 
> > > > > 您好, 我这边确实已经完成中文的适配了, 但是目前似乎还没有发现合适的中文数据集来评估这个算法的表现. 如果您知道有合适的中文数据集, 请不吝赐教!
> > > > 
> > > > 
> > > > 您好，我这边目前打算是自己标注一些数据集。其他公开的确实没有找到合适的数据集，打算试一些命名实体识别（比如https://github.com/yuankeyi/2019-SOHU-Contest ）或者实体链接数据集代替。可否请教您一下转换中文需要作哪些适配工作以及基于字粒度分词的bert您这边怎么处理span信息的嘛
> > > 
> > > 
> > > 我这边的情况也和你差不多, 我也是将中文实体标注数据集迁移过来, 作为中文版 Bert-KPE 的训练/测试数据集. 至于如何完成中文的适配, 我之前是通读下作者代码里的预处理部分, 然后 按照 中文词语 对应 英文单词的方式进行适配, 例如, 中文"开心" ---> 英文"happy", 也就是说, 我是基于词粒度, 而非字粒度分词的. 我打算最近有时间的话, 就将我的代码发布到 GitHub 上, 希望到时候可以和你交流!
> > 
> > 
> > 好的，已follow~ 希望早点可以看到您这边中文版BERT-KPE，感谢您和 @SunSiShining 的贡献~ 保持交流~
> 
> 您好, 抱歉让您久等了, 由于近期非常忙, 代码现在才提交, 我的实验代码放在 Chinese-BERT-KPE 这个 repo 里了, 整理得比较粗糙, 直接在作者的源代码上进行修改了, 希望可以交流, 谢谢!

好的，已看到~感谢您的工作，目前我这里也是被其他事情打断了，后期重新使用中可以一起维护一下，我有什么想法的话直接和您交流~
