### ISSUE TITLE
Installing the requirements.txt file does not work

### ISSUE THREAD

**Issue by bigabig** [thunlp/BERT-KPE#14]
Hi, thanks for providing the code!
Unfortunately, I cannot install all the requirements with your provided command 
```
python 3.5
pip install -r requirements.txt
```
Do you really use this outdated Python version?

The GitHub repository `-e git+https://github.com/xaynetwork/xayn_ai_research.git@23d366ff8a05eca164718a6857eb31d439d52448#egg=xain_ai_research` does not exist.

There is a version conflict of allennlp and transformers
```
The conflict is caused by:
    The user requested transformers==4.12.3
    allennlp 2.5.0 depends on transformers<4.7 and >=4.1
```

**Comment by SunSiShining** [comment]
Sorry for our late response. We have fixed the bug!

Recently we updated multilingual implementation (using the new Transformer Package) but ignored the testing of previous checkpoints. Now we restored the old version of Transformer and the folder of this package has been placed in our code (without installing the Transformer package)

Please clean up the Conda environment to infer the checkpoints. 

```
python 3.8
conda install --file conda-requirements.txt
pip install -r pip-requirements.txt
```

For any other questions please contact me via email s-sun17@mails.tsinghua.edu.cn
I check email almost every day :)
