### ISSUE TITLE
变量 max_diff_gram_num 的含义

### ISSUE THREAD

**Issue by Dielianss** [thunlp/BERT-KPE#17]
hey，孙博士好。近期我在研究KPE模型源码时，对 batchify_XXX_XXX 函数中的 变量max_diff_gram_num 有些疑惑，以 /bertkpe/dataloader)/bert2joint_dataloader.py 为例：

line 482: max_diff_gram_num = (1 + max([max(_mention_mask[-1]) for _mention_mask in mention_mask]))

这边的 max_diff_gram_num 是不是表示在 一个batch的文章中，候选关键词集合的元素数的最大值？

如果是的话，这行代码是不是可以等价于 max(phrase_list_lens) ? 因为 phrase_list_lens 即是每篇文章的候选关键词集合中包含的元素数。

**Comment by SunSiShining** [comment]
Yes, you are right. The `max_diff_gram_num` has the same value as `max(phrase_list_lens)`.

If we set the batch size to 2. 
One document under this batch has 6 **different** n-grams and the other document has 8 **different** n-grams.
Then `max_diff_gram_num` for that batch is 8.
