### ISSUE TITLE
When I ran the code, some errors occurred.

### ISSUE THREAD

**Issue by LeoGitHuber** [thunlp/BERT-KPE#18]
![image](https://user-images.githubusercontent.com/50997355/162204733-5be9be74-4dc5-4eb8-a443-f65f5b2fb561.png)
![image](https://user-images.githubusercontent.com/50997355/162204850-82360d4f-c533-4245-bf25-0be208988f49.png)
`true_score.unsqueezez(-1)` and `neg_score.unsqueeze(0)` have different sizes. But `margin_ranking_loss` requires that all input tensors have same dimension. I think there is the reason why errors occurred.

**Comment by SunSiShining** [comment]
Hi Leo, thanks for using our code.

I don't think it's a dimension error. Take the error in the figure as an example, input1 (size=[1,1]), input2 (size[1,431]), and flag (size=[1]), actually, margin_ranking_loss will scale them to the same dimensions, i.e. input1 (size=[1,431]), input2 (size=[1,431]) and flag (size=[1,431]).

Here, I try to reproduce the error, but the command ran properly without bugs. (PyTorch=1.8)
Could you provide your PyTorch version or more implementation details?

<img width="710" alt="image" src="https://user-images.githubusercontent.com/42510110/162609594-3e0edca3-2cab-400e-a4c6-cfda8e702a5a.png">

**Comment by LeoGitHuber** [comment]
@SunSiShining Thank you for your reply. My PyTorch version is 1.11.0. And I took a look at source code of PyTorch 1.8 and PyTorch 1.11. Find out that the `MarginRankingLoss` class in PyTorch 1.11 will check the input dimension before processing. I solve that problem by using 'torch.margin_ranking_loss' function.
```
input_tensor = torch.randn(3).unsqueeze(-1)
input_tensor1 = torch.randn(3).unsqueeze(0)
targe_tensor = torch.FloatTensor([1])
print(input_tensor.size())
print(input_tensor1.size())
print(torch.margin_ranking_loss(input_tensor, input_tensor1, targe_tensor, 1, 1))    # 1 stands for reduction = 'mean'
```
![image](https://user-images.githubusercontent.com/50997355/162617550-01993b9c-7c1d-495f-b9ab-5e6b148e8d4f.png)

**Comment by SunSiShining** [comment]
Wow, that's great! thanks for letting me know.
