### ISSUE TITLE
Error while running test.sh

### ISSUE THREAD

**Issue by vnik18** [thunlp/BERT-KPE#5]
Hello, thank you for this great work and for sharing your code. I am trying to run the script `test.sh` using your provided dataset and pre-trained model checkpoints, for `bert2joint`. I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 276, in <module>
    dev_candidate = candidate_decoder(args, dev_data_loader, dev_dataset, model, test_input_refactor, pred_arranger, 'dev')
  File "test.py", line 152, in bert2rank_decoder
    for step, batch in enumerate(tqdm(data_loader)):
  File "/home/ec2-user/anaconda3/envs/bert-kpe/lib/python3.5/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/ec2-user/anaconda3/envs/bert-kpe/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ec2-user/anaconda3/envs/bert-kpe/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ec2-user/anaconda3/envs/bert-kpe/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../bertkpe/dataloader/loader_utils.py", line 104, in __getitem__
    self.tokenizer, self.mode, self.max_phrase_words)
  File "../bertkpe/dataloader/bert2joint_dataloader.py", line 229, in bert2joint_converter
    src_tensor = torch.LongTensor(tokenizer.convert_tokens_to_ids(src_tokens))
TypeError: an integer is required (got type NoneType)
```

Please let me know if you have any suggestions on how to fix this. Thank you.

I am using `Python 3.5.5` and `huggingface transformers-2.5.1`.

**Comment by SunSiShining** [comment]
Sorry for our late response. Have you fixed this issue?
You can reach me via s-sun17@mails.tsinghua.edu.cn

**Comment by vnik18** [comment]
Hi, no I have to been able to fix this issue. Please let me know if you have any suggestions on how to fix this. Thank you.

**Comment by SunSiShining** [comment]
Hi, we will help you solve the problem in a few days (sorry I'm working on the ACL submission : )
I think it may be an environmental error. Our code does not need to install the Transforms package (huggingface), which is built into our code.

**Comment by SunSiShining** [comment]
Sorry again for the late reply 😃.

The problem should be the version of Huggingface Transformers.
We used its old version and the folder of this package has been placed in our code (>> bertkpe/transformers) 
Please test our code in an environment without installing Huggingface.

If you have other questions, welcome to open new issues or send me an email.
This issue has been closed.

**Comment by SunSiShining** [comment]
Sorry for our late response. We have fixed the bug!

Recently we updated multilingual implementation (using the new Transformer Package) but ignored the testing of previous checkpoints. Now we restored the old version of Transformer and the folder of this package has been placed in our code (without installing the Transformer package)

Please clean up the Conda environment to infer the checkpoints. 

```
python 3.8
conda install --file conda-requirements.txt
pip install -r pip-requirements.txt
```

For any other questions please contact me via email s-sun17@mails.tsinghua.edu.cn
I check email almost every day :)
