### ISSUE TITLE
Why include transformers?

### ISSUE THREAD

**Issue by aaronrmm** [thunlp/BERT-KPE#8]
Did you have to customize the transformers library for this task? Thanks

**Comment by SunSiShining** [comment]
Our used transformers library is the previous version without extra modification.

Considering the frequent update of the huggingface library, we directly merge its necessary modules to our codes at that time, preventing the version's incompatibility. 

Si

**Comment by SunSiShining** [comment]
If you have other questions, welcome to open new issues or send me an email.
This issue has been closed.
