### ISSUE TITLE
Using kp20k dataset

### ISSUE THREAD

**Issue by sysmetic** [thunlp/BERT-KPE#9]
dataloaders code of your own are fitted with OpenKP.
How about kp20k for tutorials?

**Comment by SunSiShining** [comment]
Hello, our code is adapted to both OpenKP and KP20k.

First, please download the original data of KP20k, then use our proposed preprocess code to conduct data preprocessing, and then modify the argument of dataset_class to KP20k when training and testing the model.

If you have other questions, welcome to open new issues or send me an email.
This issue has been closed.
